# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeAgentApp', '0002_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='worker',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
