# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeAgentApp', '0002_auto_20171003_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file_type',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
