# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeAgentApp', '0003_project_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='worker',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
