# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 08:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freeAgentApp', '0005_auto_20171016_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ThisClient', to=settings.AUTH_USER_MODEL),
        ),
    ]
