# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeAgent', '0002_auto_20170916_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.FileField(default=None, upload_to='uploads/'),
        ),
    ]
